development:
  adapter: postgresql
  database: db/development
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: disrupt11

test:
  adapter: postgresql
  database: db/test
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: disrupt11

staging:
  adapter: postgresql
  database: db/production.postgresql
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  database: db/production.postgresql
  pool: 5
  timeout: 5000

