development:
  adapter: postgresql
  database: mb/development
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: 168washu

test:
  adapter: postgresql
  database: mb/test
  pool: 5
  timeout: 5000
  port: 5432
  username: postgres
  password: 168washu

staging:
  adapter: postgresql
  database: db/production.postgresql
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  database: db/production.postgresql
  pool: 5
  timeout: 5000

