development:
  adapter: active_record
  active_record_adapter: postgresql
  host: localhost
  database: mb/development
  username: postgres
  password: disrupt11
  port: 5432

production:
  adapter: active_record
  active_record_adapter: postgresql
  <% unless ENV['DATABASE_URL'].nil? %>
  <% username, password, host, database = ENV['DATABASE_URL'].scan(%r{//(.*):(.*)@(.*)/(.*)}).first %>
  host:     <%= host %>
  username: <%= username %>
  password: <%= password %>
  database: <%= database %>
  <% end %>